// Cloudflare Workers Build uses the Astro-generated worker configuration in dist/server.
// Keep this source entry free of EmDash/R2 dependencies so local Wrangler inspection remains safe.
export default {
  fetch() {
    return new Response('Worker entry is generated by Astro Cloudflare adapter.');
  },
};
